language: cpp
compiler: gcc
sudo: false
env: PYTHON=2.7 CPP=11 GCC=4.8
addons:
  apt: 
   sources: 
      - ubuntu-toolchain-r-test
   packages:
      - gcc-4.8 
      - g++-4.8
      - cmake
  
before_script:
    - uname -a
    - printenv
    - which gcc
    - gcc-4.8 --version 2>&1 | grep gcc
    - cmake --version
    - which gcc-4.8
    - g++-4.8 --version 2>&1 | grep g++

install: 
    # Install gtest without sudo 
    - export LIBRARY_PATH=$(pwd)
    - env | grep LD

script:
    - ls -alh
    - df -h
    - free -h
    - echo "Hello script"
    - python --version
    - pwd
