language: cpp
compiler: gcc
sudo: false
addons:
  apt: 
   sources: 
      - ubuntu-toolchain-r-test
   packages:
      - gcc-4.8 
      - g++-4.8
      - cmake
  
before_script:
    - uname -a
    - printenv
    - which gcc
    - g++ --version 2>&1 | grep g++
    - gcc --version 2>&1 | grep gcc
    - cmake --version
    - which gcc-4.8

install: 
    # Install gtest without sudo 
    - mkdir ~/gtest && cd ~/gtest
    - export LIBRARY_PATH=$(pwd)

script:
    - ls -al
    - echo "Hello script"