language: cpp
sudo: required
dist: trusty

#env: PYTHON=2.7 CPP=11 GCC=4.8
#addons:
#  apt: 
#   sources: 
#      - ubuntu-toolchain-r-test
#   packages:
#      - gcc-4.8 
#      - g++-4.8
#      - cmake

notifications:
  email: true
  
before_script:
    - uname -a
    - printenv
    - which gcc
    - gcc --version 2>&1 | grep gcc
    - cmake --version
    - which gcc
    - which gcc-4.8
    - g++-4.8 --version 2>&1 | grep g++

before_install:
    - pip install --user --upgrade pip virtualenv
    - virtualenv -p python2.7 venv
    - source venv/bin/activate
    - ./install-lis.sh

install: 
    # Install gtest without sudo 
    - export LIBRARY_PATH=$(pwd)
    - env | grep LD
    - pip install numpy scipy pytest

script:
    - pwd
    - ls -alh
    - df -h
    - free
    - python --version
    - python2.7 --version
    - python2.7  -c "import numpy"
    - ls -alhR /usr/local
    
