language: cpp
sudo: false
matrix:
  include:
  - os: linux
    env: PYTHON=2.7 CPPV=11 GCC=4.8
    addons:
      apt:
        sources: [ubuntu-toolchain-r-test, kubuntu-backports]
        packages: [g++-4.8, cmake]
  - os: linux
    env: PYTHON=3.5 CPPV=11 GCC=4.8
    addons:
      apt:
        sources: [ubuntu-toolchain-r-test, kubuntu-backports, deadsnakes]
        packages: [g++-4.8, cmake, python3.5-dev]
  - sudo: true
    services: docker
    env: PYTHON=2.7 CPPV=14 GCC=6
  - sudo: true
    services: docker
    env: PYTHON=3.5 CPPV=14 GCC=6
  - os: osx
    osx_image: xcode7.3
    env: PYTHON=2.7 CPPV=14 CLANG
  - os: osx
    osx_image: xcode7.3
    env: PYTHON=3.5 CPPV=14 CLANG
  # A barebones build makes sure everything still works without optional deps (numpy/scipy/eigen)
  # and also tests the automatic discovery functions in CMake (Python version, C++ standard).
  - os: linux
    env: BAREBONES
    addons:
      apt:
        sources: [ubuntu-toolchain-r-test, kubuntu-backports]
        packages: [g++-4.8, cmake]
    install: pip install pytest
# Documentation build:
    #  - os: linux
    #    language: docs
    #    env: DOCS STYLE
    #    install: pip install sphinx sphinx_rtd_theme
    #    script:
    #    - make -C docs html SPHINX_OPTIONS=-W
    #    - tools/check-style.sh
cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/Library/Caches/pip
before_install:
- |
  # Configure build variables
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    if [ -z "$GCC" ]; then export GCC=4.8; fi
    export CXX=g++-$GCC CC=gcc-$GCC;
    if [ "$GCC" = "6" ]; then export DOCKER=debian:testing CXX=g++ CC=gcc; fi
  elif [ "$TRAVIS_OS_NAME" = "osx" ]; then
    export CXX=clang++ CC=clang;
  fi
  if [ -n "$CPPV" ]; then export CPPV=-std=c++$CPPV; fi
  if [ "${PYTHON:0:1}" = "3" ]; then export PY=3; fi
- |
  # Initialize enviornment
  if [ -n "$DOCKER" ]; then
    docker pull $DOCKER
    export containerid=$(docker run --detach --tty \
      --volume="$PWD":/pybind11 --workdir=/pybind11 \
      --env="CC=$CC" --env="CXX=$CXX" --env="DEBIAN_FRONTEND=$DEBIAN_FRONTEND" \
      --env=GCC_COLORS=\  \
      $DOCKER)
    docker exec --tty "$containerid" sh -c 'for s in 0 15; do sleep $s; apt-get update && apt-get -qy dist-upgrade && break; done'
    export SCRIPT_RUN_PREFIX="docker exec --tty $containerid"
  else
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      pip install --user --upgrade pip virtualenv
      virtualenv -p python$PYTHON venv
    elif [ "$TRAVIS_OS_NAME" = "osx" ]; then
      if [ "$PY" = "3" ]; then
        brew update; brew install python$PY;
      else
        curl -fsSL -O https://bootstrap.pypa.io/get-pip.py
        sudo -H python get-pip.py
      fi
      pip$PY install --user --upgrade pip virtualenv
      python$PY -m virtualenv venv
    fi
    source venv/bin/activate
  fi
install:
- |
  # Install dependencies
  if [ -n "$DOCKER" ]; then
    docker exec --tty "$containerid" sh -c "for s in 0 15; do sleep \$s; apt-get -qy --no-install-recommends install \
      python$PYTHON-dev python$PY-pytest python$PY-scipy python$PY-numpy \
      libeigen3-dev cmake make g++ && break; done"
  else
    pip install numpy scipy pytest
  fi
  ./install-lis.sh
  export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/lis/lib
  
script:
- $SCRIPT_RUN_PREFIX git clone https://github.com/pybind/pybind11.git
- $SCRIPT_RUN_PREFIX pwd
- $SCRIPT_RUN_PREFIX ls -alh
- $SCRIPT_RUN_PREFIX ./clean.sh
- $SCRIPT_RUN_PREFIX python --version
- $SCRIPT_RUN_PREFIX python$PY --version
- $SCRIPT_RUN_PREFIX python$PY build.py build_ext --inplace
- $SCRIPT_RUN_PREFIX python$PY csr_test.py
- $SCRIPT_RUN_PREFIX cat residuals.log

after_script:
- if [ -n "$DOCKER" ]; then docker stop "$containerid"; docker rm "$containerid"; fi
